name: skyflow_android
description: Stripe platform implementation for Android
version: 0.1.7
homepage: 'https://www.skyflow.com/'

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3

flutter:
  plugin:
    platforms:
      android:
        package: com.flutter.skyflow
        pluginClass: SkyflowAndroidPlugin
