name: skyflow_example
description: Demonstrates how to use the skyflow plugin.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  skyflow_ios: 
    path: ../packages/skyflow_ios
  font_awesome_flutter: ^9.2.0
  platform: ^3.0.0


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
