name: skyflow_flutter
description: Flutter library for Skyflow. Supports PaymentSheets, Apple & Google Pay, SCA, PSD2 and much more.
version: 0.4.4
homepage: https://github.com/hostel-hop/skyflow_flutter
repository: https://github.com/hostel-hop/skyflow_flutter

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: skyflow_android
      ios:
        default_package: skyflow_ios

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  skyflow_ios: ^0.1.3
  skyflow_android: ^0.1.6
  skyflow_platform_interface: ^9.4.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  pubspec_dependency_sorter: ^1.0.4
