name: skyflow_flutter
description: Flutter library for Skyflow. Supports PaymentSheets, Apple & Google Pay, SCA, PSD2 and much more.
version: 0.2.2
homepage: https://github.com/hostel-hop/skyflow_flutter
repository: https://github.com/hostel-hop/skyflow_flutter

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      ios:
        default_package: skyflow_ios

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  skyflow_ios: ^0.0.8
  skyflow_platform_interface: ^9.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1